#port
quarkus.http.port=8085
quarkus.package.jar.type=fast-jar

# Hibernate and Datasource configuration
quarkus.datasource.db-kind=${DB_TYPE}
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.packages=com.freded.entities


# Keycloak OIDC configuration
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/${KEYCLOAK_REALM}
keycloak.realm=${KEYCLOAK_REALM}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.scope=${KEYCLOAK_SCOPE}

