
quarkus.package.jar.type=fast-jar


# Keycloak OIDC configuration
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/${KEYCLOAK_REALM}
keycloak.realm=${KEYCLOAK_REALM}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.application-type=service
